### ISSUE TITLE
How to use with PSK?

### ISSUE THREAD

**Issue by binoculars** [PolymerElements/iron-scroll-threshold#10]
### Description

I've tried a number of ways to use iron-scroll-threshold with iron-list in the Polymer Starter Kit (PSK)--specifically the Big Sur demo is relevant. I cannot get it to work beyond the first load. I _am_ using the `clearTriggers()` method in the ajax response. I'm not sure if it's because the element is inside of paper-scroll-header-panel or not. Please clarify this if you can.

### Expected outcome

The on-lower-threshold event is fired on scroll to bottom.

### Actual outcome

The on-lower-threshold event only fires once

### Steps to reproduce
1. Copy & paste Big Sur example into a section of the PSK.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by blasten** [comment]
Yes. that won't work. You could either use app-layout elements or structure the `iron-scroll-threshold` as follow:
1.  https://github.com/PolymerElements/iron-scroll-threshold/blob/master/demo/scrolling-region.html 
2. set an id on the iron-scroll-threshold. e.g. `scrollThreshold`
3. Override the `scroller` property of paper-scroll-header-panel to point to the `iron-scroll-threshold` reference.    e.g.  `pshp.scroller = this.$.scrollThreshold;`

Feel free to reopen if you find an issue.
