### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by ankon** [PolymerElements/iron-scroll-threshold#19]
### Description

The version of this component is at 1.0.2, since then a few months have passed and two issues fixed: #8, #16. 

### Expected outcome

An officially released version is available via bower.

### Actual outcome

It is not possible to get updates to this component via regular bower versions, but one must point to the git 'master' branch in `bower.json`.

**Comment by blasten** [comment]
Done: https://github.com/PolymerElements/iron-scroll-threshold/releases/tag/v1.0.3
