### ISSUE TITLE
Use IntersectionObserver if available

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-scroll-threshold#2]
`IntersectionObserver` is now in Chrome 49 (you might have to have the experiment web platform features flag on). We should use this API if feature detected. It's perfect for this use case and will be great for perf!

**Comment by blasten** [comment]
I tried using `IntersectionObserver`. The main issue is that it would require to create & observe two DOM elements so that I can get notifications when the thresholds have been reached.  I'd chat with the team. Thanks for pointing that out though.

**Comment by blasten** [comment]
After chatting with @ojanvafai we concluded that the use case for `iron-scroll-threshold` is slightly different and `IntersectionObserver` may not help to improve performance.
