### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by taniarv** [PolymerElements/iron-scroll-threshold#6]
I am just trying to use this component with an iron-list, very simple: 

```
<iron-scroll-threshold on-lower-threshold="bottomReached" id="threshold">
      <iron-list scroll-target="threshold" items="{{news}}" as="item">
        <template>
          <div>AAAAAAA</div>
        </template>
      </iron-list>
    </iron-scroll-threshold>
```

I have defined a function bottomReached, that right now is just logging to the console to check everything is working fine. 

```
....
  bottomReached: function(e){
    console.log('Bottom reached!')
  }
....
```

I get the first logger, once the page is loaded. But then I scroll, and nothing happens. 
The console is showing the following error (it appears before the console log)

`Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

Why is it failing? I am testing it in Chrome v 48.0.2564.109 (64-bit)

**Comment by dhrytsenko** [comment]
I have the same problem when want to add attribute `scroll-target` to the `iron-list`

**Comment by frankiefu** [comment]
@taniarv , I can't reproduce the issue with the latest `iron-list` (v1.2.4) and `iron-scroll-threshold`.  Here is my test: http://jsbin.com/xomowoyeli/edit?html,console,output

**Comment by blasten** [comment]
@taniarv yeah. please update your dependencies to make sure you have the latest ones.

**Comment by blasten** [comment]
Please reopen if this is still an issue.
